//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MESA_SOPORTEEntities : DbContext
    {
        public MESA_SOPORTEEntities()
            : base("name=MESA_SOPORTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DEPARTAMENTO> TBL_DEPARTAMENTO { get; set; }
        public virtual DbSet<TBL_ESTADO> TBL_ESTADO { get; set; }
        public virtual DbSet<TBL_INCIDENTE> TBL_INCIDENTE { get; set; }
        public virtual DbSet<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
        public virtual DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public virtual DbSet<TBL_PRIORIDAD> TBL_PRIORIDAD { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
