//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INCIDENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INCIDENTE()
        {
            this.TBL_OBSERVACION = new HashSet<TBL_OBSERVACION>();
        }
    
        public int INC_ID { get; set; }
        public Nullable<System.DateTime> INC_FECHA { get; set; }
        public Nullable<System.DateTime> INC_VIGENCIA { get; set; }
        public string INC_NUMTICKET { get; set; }
        public string INC_COMENTARIO { get; set; }
        public string INC_TIPO { get; set; }
        public Nullable<int> INC_STATUS { get; set; }
        public Nullable<int> INC_PRIORIDAD { get; set; }
        public Nullable<int> INC_USUARIO { get; set; }
        public Nullable<System.DateTime> INC_ADD { get; set; }
    
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        public virtual TBL_PRIORIDAD TBL_PRIORIDAD { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
    }
}
