//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONA()
        {
            this.TBL_OBSERVACION = new HashSet<TBL_OBSERVACION>();
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
    
        public int PER_ID { get; set; }
        public Nullable<int> DEP_ID { get; set; }
        public string PER_TIPOIDENTIFICACION { get; set; }
        public string PER_IDENTIFICACION { get; set; }
        public string PER_APELLIDOS { get; set; }
        public string PER_NOMBRES { get; set; }
        public string PER_DIRECCION { get; set; }
        public string PER_TELEFONO { get; set; }
        public string PER_EMAIL { get; set; }
        public Nullable<System.DateTime> PER_ADD { get; set; }
        public Nullable<int> PER_STATUS { get; set; }
    
        public virtual TBL_DEPARTAMENTO TBL_DEPARTAMENTO { get; set; }
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
