//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ESTADO()
        {
            this.TBL_DEPARTAMENTO = new HashSet<TBL_DEPARTAMENTO>();
            this.TBL_INCIDENTE = new HashSet<TBL_INCIDENTE>();
            this.TBL_OBSERVACION = new HashSet<TBL_OBSERVACION>();
            this.TBL_PERSONA = new HashSet<TBL_PERSONA>();
            this.TBL_PRIORIDAD = new HashSet<TBL_PRIORIDAD>();
            this.TBL_ROL = new HashSet<TBL_ROL>();
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
        }
        [Display(Name = "Código")]
        public int EST_ID { get; set; }
        [Display(Name = "Descripción")]
        [Required]
        public string EST_DESCRIPCION { get; set; }

        [Display(Name = "Estado")]
        public string EST_STATUS { get; set; }


        [Display(Name = "Fecha creación")]
        public Nullable<System.DateTime> EST_ADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEPARTAMENTO> TBL_DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INCIDENTE> TBL_INCIDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERSONA> TBL_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRIORIDAD> TBL_PRIORIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ROL> TBL_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
