//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRIORIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRIORIDAD()
        {
            this.TBL_INCIDENTE = new HashSet<TBL_INCIDENTE>();
        }
    
        public int PRI_ID { get; set; }
        public string PRI_NOMBRE { get; set; }
        public Nullable<int> PRI_STATUS { get; set; }
        public Nullable<System.DateTime> PRI_ADD { get; set; }
    
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INCIDENTE> TBL_INCIDENTE { get; set; }
    }
}
