//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI6_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPARTAMENTO()
        {
            this.TBL_PERSONA = new HashSet<TBL_PERSONA>();
        }
    
        public int DEP_ID { get; set; }
          [Display(Name = "Código")]
        public string DEP_DESCRIPCION { get; set; }
        [Display(Name = "Descripción")]
        [Required]
        public string DEP_DIRRECCION { get; set; }
        [Display(Name = "Dirección")]
        [Required]
        public Nullable<System.DateTime> DEP_ADD { get; set; }
        [Display(Name = "Fecha creación")]
        [Required]
        public Nullable<int> DEP_STATUS { get; set; }
        [Display(Name = "Estado")]
        [Required]
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERSONA> TBL_PERSONA { get; set; }
    }
}
